### PR TITLE
fix: restore span context on async call to query.then

### LINKED ISSUE #29: Using with express async-await controller creates unlinked spans
Hey! First thing, thanks for taking the time and effort for creating this plugin.

I noticed using async-await on the query does not link the mongoose span with the express span unless the query is executed with `exec()`.

Here are some example:

### Using then() - Links correctly
```js
app.get('/mongo-then', (_req, res) => {
  userCollection.findOne({}).then((u) => res.status(200).send(u));
});
```

### Using async-await with exec - Links correctly
```js
app.get('/mongo-exec', async (_req, res) => {
  const user = await userCollection.findOne({}).exec();
  res.status(200).send(user);
});
```  

<hr/>

### Using async-await - Created 2 separate spans   

* 1 span called `get /mongo-async-await`.
* 1 span called `mongoose.users.findOne`. 

```js
app.get('/mongo-async-await', async (_req, res) => {
  const u = await userCollection.findOne({});
  res.status(200).send(u);
});
```

Zipkin Screenshot:

image

  
<hr/>   
  

I'm using TypeScript, attaching my set up for reference:  
Typescript version: **3.8.3**
tsconfig:
```json
{
    "compilerOptions": {
        "target": "ES2017",
        "lib": ["ES2019", "DOM"],
        "rootDir": "lib",
        "outDir": "dist",
        "module": "commonjs",
        "moduleResolution": "node",
        "strict": false,
        "declaration": true,
        "sourceMap": true,
        "inlineSources": true,
        "types": ["node"],
        "allowSyntheticDefaultImports": true,
        "esModuleInterop": true
    }
}
```

### PR DESCRIPTION
**Pull request by BlumAmir**
fixes #29 

mongoose [Query](https://github.com/Automattic/mongoose/blob/master/lib/query.js) object is 'Thenable' - it has a [then](https://github.com/Automattic/mongoose/blob/master/lib/query.js#L4432) function which is called when query is awaited like this: `await User.findOne(...)` (findOne returns a Query object).
This function internally calls the instrumented `exec()` function which [start a new span](https://github.com/wdalmut/opentelemetry-plugin-mongoose/blob/master/src/utils.ts#L7) for the operation. The [startSpan](https://github.com/open-telemetry/opentelemetry-js/blob/master/packages/opentelemetry-tracing/src/Tracer.ts#L63) function has `context` parameter, which is not set, thus get [the default value](https://github.com/open-telemetry/opentelemetry-js/blob/master/packages/opentelemetry-tracing/src/Tracer.ts#L66) from the `ContextManager` by calling `api.context.active()`

Open telemetry uses the `async_hooks` library to trace async operation and [return the right active context](https://github.com/open-telemetry/opentelemetry-js/blob/master/packages/opentelemetry-context-async-hooks/src/AsyncHooksContextManager.ts#L65) across async/await function calls. This behaviour relies on the `asyncHooks.executionAsyncId()` function which works for native promise, but return 0 in case of thenables (at least in the specific context of issue #29), causing the new span in `exec()` to have [root context](https://github.com/open-telemetry/opentelemetry-js/blob/05e7bb9c8fbbc8b36200c3b10b463f331a31a6f7/packages/opentelemetry-context-async-hooks/src/AsyncHooksContextManager.ts#L67) and break the link to it's real parent span.

To fix the issue, I patched the relevant Query functions so they capture the active span for the query, store it on the Query object, and then restore it when `then` is called.

### CODE REVIEW

**Comment by wdalmut** [comment]
I think that this one is related to #30 

Can you add this test case?

```
    it("instrumenting combined operation with Promise.all", async (done) => {
      const span = provider.getTracer('default').startSpan('test span');
      provider.getTracer('default').withSpan(span, () => {
        Promise.all([
          User
          .find({id: "_test"})
          .skip(1)
          .limit(2)
          .sort({email: 'asc'}),
          User.countDocuments()
        ])
          .then((users) => {
            // close the root span
            span.end()

            const spans: ReadableSpan[] = memoryExporter.getFinishedSpans();

            // same traceId assertion
            expect([...new Set(spans.map((span: ReadableSpan) => span.spanContext.traceId))].length).toBe(1)

            expect(spans.length).toBe(3)

            assertSpan(spans[0])
            assertSpan(spans[1])

            expect(spans[0].attributes[AttributeNames.DB_MODEL_NAME]).toEqual('User')
            expect(spans[0].attributes[AttributeNames.DB_QUERY_TYPE]).toMatch(/^(find|countDocuments)$/g)

            expect(spans[1].attributes[AttributeNames.DB_MODEL_NAME]).toEqual('User')
            expect(spans[1].attributes[AttributeNames.DB_QUERY_TYPE]).toMatch(/^(find|countDocuments)$/g)

            done()
          })
      })
    })

    it("instrumenting combined operation with async/await", async (done) => {
      const span = provider.getTracer('default').startSpan('test span');
      provider.getTracer('default').withSpan(span, async () => {
        await User.find({id: "_test"}).skip(1).limit(2).sort({email: 'asc'})
        // close the root span
        span.end()

        const spans: ReadableSpan[] = memoryExporter.getFinishedSpans();

        expect(spans.length).toBe(2)

        // same traceId assertion
        expect([...new Set(spans.map((span: ReadableSpan) => span.spanContext.traceId))].length).toBe(1)

        assertSpan(spans[0])

        expect(spans[0].attributes[AttributeNames.DB_MODEL_NAME]).toEqual('User')
        expect(spans[0].attributes[AttributeNames.DB_QUERY_TYPE]).toEqual('find')

        done()
      })
    })
```

**Comment by wdalmut** [comment]
@BlumAmir thanks for this PR this also fixes #30 

I review deeply this commit and i will merge ti asap.

Thank you again for this.

File: src/mongoose.ts [hunk 1]
```diff
@@ -103,11 +128,45 @@ export class MongoosePlugin extends BasePlugin<typeof mongoose> {
...
+    }
+  }
+
+  private patchQueryThen() {
+    const thisPlugin = this
+    thisPlugin._logger.debug('MongoosePlugin: patched mongoose query then prototype');
+    return (originalThen: Function) => {
+      return function patchedThen(this: any) {
+        if(this._otContext) {
+          return thisPlugin._tracer.withSpan(this._otContext, () => {
```
Comment (vmarchaud) [inline src/mongoose.ts:148]: you could replace that by `thisPlugin._tracer.bind(this._otContext, originalThen)` (interally it does almost the same but it would be clearer for you i think)

**Comment by BlumAmir** [comment]
Hi @wdalmut , thanks for the review and for adding more tests.
Sorry for the delay, I was away for 2 days

File: src/mongoose.ts (hunk 1 above)
Comment (BlumAmir) [reply src/mongoose.ts:148]: Good comment, thank you
