### PR TITLE
Fixes #15 - Model.create uses internal save with callback function

### LINKED ISSUE #15: Method `Model.create` fails with error
If we use the method  `Model.create` the library breaks the flow

```js
ModelName.create({/** payload */}).then(/** logic */)
```

### PR DESCRIPTION
**Pull request by wdalmut**

### CODE REVIEW

File: src/mongoose.ts [hunk 1]
```diff
@@ -73,9 +75,28 @@ export class MongoosePlugin extends BasePlugin<typeof mongoose> {
...
-          .catch(handleError(span))
-          .finally(() => span.end() )
+        if (options instanceof Function) {
+          fn = options
+          options = undefined
+        }
+
+        if (fn instanceof Function) {
+          return originalSave.apply(this, [options, (err: any, product: any) => {
+            if (err) {
```
Comment (wdalmut) [inline src/mongoose.ts:85]: Need to handle errors using the `utils` package
